/* eslint-disable */
require('./agency-structure-active')
require('./biling-finance-active')
require('./candidates-active')
require('./clients-locations-active')
require('./dashboard-active')
require('./documents-compliance-active')
require('./internal-users-active')
require('./job-schedule-active')
require('./menu_narrow')
require('./menu')
require('./rate-edit')
require('./reporting-active')
require('./rotate-ipad')
require('./rules-definitions-active')
