/* eslint-disable */
require('./connection')
require('./cut-tool-active')
require('./cut-tool-disabled')
require('./cut-tool-normal')
require('./delete-active copy')
require('./delete-active')
require('./delete-disabled')
require('./delete-normal')
require('./drag-normal')
require('./edit-active')
require('./edit-disabled')
require('./edit-normal')
require('./edit')
require('./line-full')
require('./line-half')
require('./line-l')
require('./merge-tool-active')
require('./merge-tool-disabled')
require('./merge-tool-normal')
require('./move-tool-active')
require('./move-tool-disabled')
require('./move-tool-normal')
require('./reset-tool-active')
require('./reset-tool-disabled')
require('./reset-tool-normal')
